AWSTemplateFormatVersion: 2010-09-09

Parameters:
    TableName:
        Type: String

Resources:
    DbCloudwatchMetrics:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: Retain
        Properties:
            TableName: !Ref TableName
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                -
                  AttributeName: namespace
                  AttributeType: S
                -
                  AttributeName: date
                  AttributeType: S
            KeySchema:
                -
                  AttributeName: namespace
                  KeyType: HASH
                -
                  AttributeName: date
                  KeyType: RANGE
            TimeToLiveSpecification:
                AttributeName: expire_at
                Enabled: true
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES

    CwMockRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - lambda.amazonaws.com
              Action:
              - sts:AssumeRole
          Path: "/"
          Policies:
          - PolicyName: root
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                - 'dynamodb:*'
                Resource: '*'

    CwStreamHandlerFunction:
        Type: AWS::Lambda::Function
        DependsOn: [ CwMockRole ]
        Properties:
            FunctionName: cloudwatch-stream-handler
            MemorySize: 128
            Handler: index.handler
            Role: !GetAtt CwMockRole.Arn
            Runtime: nodejs6.10
            Timeout: 300
            Environment:
                Variables:
                    table_name: !Sub "${TableName}"
            Code:
                ZipFile: >
                    console.log('Loading function');
                    var AWS = require('aws-sdk');

                    exports.handler = function(event, context) {
                        console.log(JSON.stringify(event,null,"\t"))
                        context.done();
                    };

    SendersTableStream:
       Type: AWS::Lambda::EventSourceMapping
       Properties:
         BatchSize: 1
         EventSourceArn: !GetAtt DbCloudwatchMetrics.StreamArn
         FunctionName: !Ref CwStreamHandlerFunction
         StartingPosition: TRIM_HORIZON
